name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.2'
        registry-url: 'https://registry.npmjs.org'

    - name: Get path to yarn cache
      id: yarn-cache-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install node_modules
      run: yarn install --prefer-offline

    - name: Configure .env for prod
      run: |
        touch .env
        printf "${{ secrets.PROD_ENV }}" >> .env

    - name: Build
      run: yarn build

    - name: Release
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SCP_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: ${{ secrets.DEPLOY_DIR }}
        strip_components: 1
